Level 1: Basics
1.

Create a NumPy array from 1 to 20, then:

print only even numbers

print numbers greater than 10

In [1]:
import numpy as np

In [12]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr=np.arange(0,21,1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
mask=arr>10
arr[mask]


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

2.

Create an array:

[1, 2, 3, 4, 5]

Then:

convert it to float32

print number of bytes used

In [ ]:
arr=np.array([[1, 2, 3, 4, 5]],dtype=np.float32)
arr

array([[1, 2, 3, 4, 5]])

In [17]:
arr.nbytes

20

3.

Create a 3x3 matrix filled with:

zeros

ones

value = 7

In [18]:
zeros=np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
full=np.full((3,3),5)
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

4.

Create two arrays:

one using arange

one using linspace

Make them produce similar ranges and compare.

In [22]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [25]:
b=np.linspace(0,8,5)
b

array([0., 2., 4., 6., 8.])

Level 2: Indexing & Slicing
5.

Given:

x = np.arange(10)

Do:

reverse it

get elements at odd indices

get elements from index 3 to 7

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[-1:0:-2]

array([9, 7, 5, 3, 1])

In [31]:
x[1::2]

array([1, 3, 5, 7, 9])

In [32]:
x[3:8]

array([3, 4, 5, 6, 7])

6.

Given:

x2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

Extract:

first row

last column

first 2 rows and first 3 columns

In [33]:
x2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
x2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
x2[0]

array([1, 2, 3, 4])

In [37]:
x2[:,-1]

array([ 4,  8, 12])

In [38]:
x2[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

Level 3: Views vs Copies ⚠️
8.

Create a 3x3 array, then:

take a slice (top-left 2x2)

modify it

print original

👉 Explain what happened.

In [39]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sub=arr[0:2,0:2]
sub

array([[1, 2],
       [4, 5]])

In [41]:
sub[0,0]=99
sub

array([[99,  2],
       [ 4,  5]])

In [42]:
arr

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

9.

Fix the previous problem using .copy().

In [43]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
sub=arr[0:2,0:2].copy()
sub

array([[1, 2],
       [4, 5]])

In [45]:
sub[0,0]=99
sub

array([[99,  2],
       [ 4,  5]])

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Level 4: Reshape & Dimensions
10.

Create:

arr = np.arange(1, 13)

Then:

reshape to (3,4)

reshape to (2,6)

try invalid reshape and handle error

In [66]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
arr2=arr.reshape(-1)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
arr3=arr.reshape(12,1)
arr3

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

11.

Convert:

x = np.array([1,2,3])

to:

row vector

column vector

In [60]:
x = np.array([1,2,3]).reshape(1,-1)
x

array([[1, 2, 3]])

In [61]:
x.shape

(1, 3)

In [53]:
x.ndim

1

In [54]:
row_vector=x[np.newaxis,:]
row_vector

array([[1, 2, 3]])

In [55]:
row_vector.ndim

2

In [68]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [69]:
rx=x.reshape(-1,1)
rx

array([[1],
       [2],
       [3]])

In [70]:
nx=x[:,np.newaxis]
nx

array([[1],
       [2],
       [3]])

12.

Check if reshape returns a view:

modify reshaped array

print original

In [71]:
arr=np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
reshaped=arr.reshape(2,4)
reshaped

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
reshaped[0,0]=100
reshaped

array([[100,   2,   3,   4],
       [  5,   6,   7,   8]])

In [74]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8])

In [ ]:
a=np.arange(6)
b=a.reshape(2,3)
a

array([0, 1, 2, 3, 4, 5])

In [76]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
b.base is a

True

In [ ]:
a=np.arange(6) 
c=a[::2] 
d=c.reshape(3,1)


In [80]:
a

array([0, 1, 2, 3, 4, 5])

In [88]:
c

array([0, 2, 4])

In [83]:
d

array([[0],
       [2],
       [4]])

In [85]:
d.base is c

False

Level 5: Random & Attributes
13.

Generate:

3x3 uniform random array

3x3 normal distribution

Then print:

shape

ndim

size

dtype

In [89]:
a=np.random.random((3,3))
a

array([[0.49365492, 0.16124944, 0.93500609],
       [0.29963311, 0.2949149 , 0.67447564],
       [0.9304165 , 0.83947309, 0.3441993 ]])

In [90]:
b=np.random.normal(0,1,(3,3))
b

array([[-0.76894583,  2.34201602,  0.49106262],
       [-2.03143816, -1.76998075,  1.24909434],
       [ 1.4198285 ,  0.20585453, -0.70150469]])

In [91]:
a.shape

(3, 3)

In [92]:
a.ndim

2

In [93]:
a.size

9

In [94]:
a.dtype

dtype('float64')

14.

Use a fixed seed to generate random numbers twice
→ prove they are identical.

In [99]:
r=np.random.default_rng(10)
a=r.integers(10,size=5)
r=np.random.default_rng(10)
b=r.integers(10,size=5)
print(a)
b

[7 9 2 2 7]


array([7, 9, 2, 2, 7], dtype=int64)

Level 6: Concatenation & Splitting
15.

Given:

a = np.array([1,2,3])
b = np.array([4,5,6])

concatenate them

stack vertically

stack horizontally

In [109]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a

array([1, 2, 3])

In [101]:
b

array([4, 5, 6])

In [102]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [103]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

16.

Given:

grid = np.arange(16).reshape(4,4)

split into upper and lower

split into left and right

In [114]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
upper,lower=np.vsplit(grid,[4])
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [123]:
lower

array([], shape=(0, 4), dtype=int32)

In [117]:
upper,lower=np.hsplit(grid,[3])

In [118]:
upper

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [119]:
lower

array([[ 3],
       [ 7],
       [11],
       [15]])

Level 7: Real Thinking
17.

Create a 5x5 matrix where:

borders = 1

inside = 0

In [124]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [126]:
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

18.

Create a matrix and:

replace all values > 5 with 100

In [135]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
mask=arr%2==0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [137]:
arr[mask]

array([0, 2, 4, 6, 8])

19.

From:

x = np.arange(10)

Create:

[0, 1, 2]
[1, 2, 3]
[2, 3, 4]
...

(similar to sliding window 👀)

In [138]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
result=np.array([x[i:i+3] for i in range(len(x)-2)])
result

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

Level 8: Tricky / Advanced
20.

Without loops:

create array of numbers 1 → 10

square only even numbers

In [145]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [146]:
mask=arr%2==0
arr[mask]=arr[mask]**2
arr

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100])

21.

Find:

min

max

mean
for a random 10x10 array

In [147]:
arr=np.random.random((10,10))
arr

array([[0.3106714 , 0.98944917, 0.10929952, 0.76495338, 0.7627843 ,
        0.49227822, 0.98910237, 0.91842431, 0.40036843, 0.2983076 ],
       [0.73474005, 0.73144416, 0.60668258, 0.64001816, 0.36816635,
        0.66220851, 0.64097782, 0.66551715, 0.30080117, 0.81750222],
       [0.05563752, 0.30926844, 0.54846945, 0.20865586, 0.59383079,
        0.38656982, 0.14422195, 0.18648436, 0.8292257 , 0.85173486],
       [0.87718843, 0.46033842, 0.53523305, 0.92953282, 0.13434321,
        0.25918037, 0.65294273, 0.28091086, 0.14389472, 0.83956812],
       [0.95652074, 0.19993896, 0.73989313, 0.31521881, 0.47761672,
        0.25275151, 0.37684033, 0.66389169, 0.30484512, 0.53790121],
       [0.58594881, 0.85242728, 0.77019855, 0.76980655, 0.12137782,
        0.33837648, 0.9762482 , 0.2367412 , 0.40380868, 0.60042417],
       [0.22378976, 0.08309879, 0.67173218, 0.67717864, 0.7520073 ,
        0.22438546, 0.59288059, 0.6558558 , 0.62399371, 0.56129661],
       [0.62567959, 0.92573995, 0.5226850

In [148]:
arr.min()

0.035698861764324796

In [149]:
arr.max()

0.9894491693230023

In [150]:
np.max(arr)

0.9894491693230023

In [151]:
np.mean(arr)

0.529226428208859

22.

Create a 2D array and:

normalize it between 0 and 1

In [152]:
arr=np.array([1,2,4,8])
mn=arr.min()
mx=arr.max()
norm=(arr-mn)/(mx-mn)
norm


array([0.        , 0.14285714, 0.42857143, 1.        ])

23.

Show the difference between:

a = np.array([1,2,3])
b = a
c = a.copy()

Modify b and c and explain result.